. 'D:\Projects\Kelola Konten\website\marketing\article-gen.ps1'
Write-Article @{Slug='tools-media-sosial-untuk-agensi';Title='Tools Media Sosial untuk Agensi: Rubrik Evaluasi yang Tidak Terjebak Demo';Primary='tools media sosial untuk agensi';Eyebrow='Panduan agensi';Intro='Agensi membutuhkan lebih dari tombol schedule. Mereka perlu workspace per klien, approval, jejak perubahan, status permission, dan cara menjelaskan laporan. Rubrik ini membantu membandingkan alat secara jujur tanpa mengarang harga, jumlah channel, atau fitur kompetitor.';Sections=@(
 @{h='Definisikan pekerjaan agency';p=@('Buat daftar alur nyata: menerima brief, membuat draft, meminta aset, review klien, menjadwalkan, menangani gagal, dan melaporkan hasil. Alat yang terlihat lengkap pada demo dapat tetap menyulitkan jika satu alur harus dipindahkan ke spreadsheet.','Pisahkan kebutuhan yang wajib pada hari pertama dari roadmap. Workspace dan approval biasanya diperlukan sebelum laporan cantik. Unified inbox, competitor analytics, dan PDF branded Kelola Konten masih `segera` sampai bukti implementasi tersedia.','Minta setiap alat menjelaskan siapa pemilik data, bagaimana export dilakukan, dan apa yang terjadi ketika akses provider dicabut. Jawaban ini sering lebih penting daripada daftar ikon channel.')};
 @{h='Nilai workspace dan isolasi';p=@('Setiap klien idealnya memiliki workspace atau customer boundary. Uji apakah user dapat melihat kalender, media, dan analytics klien lain. Uji juga role owner, editor, reviewer, dan read-only.','Postiz source memiliki organisasi, customer, integration, dan team surface. Kelola Konten tetap wajib menjalankan uji isolasi API, bukan hanya mengandalkan menu yang berbeda.','Undang reviewer dengan link atau email yang dapat dicabut. Audit event menyimpan siapa yang melakukan perubahan. Jika alat hanya mengandalkan label manual, catat risikonya.')};
 @{h='Nilai approval dan feedback';p=@('Approval yang baik menyimpan komentar dekat dengan draft, versi aset, status, dan timestamp. Perubahan substansial mengembalikan post ke review.','Tanyakan apakah klien dapat memberi feedback tanpa memperoleh akses ke integration settings. Tanyakan juga apakah komentar internal berbeda dari komentar publik. Perbedaan ini harus terlihat di UI.','Kelola Konten menggunakan internal comments pada beta. Jika klien membutuhkan external inbox, labeli `segera` dan berikan handoff. Jangan menjual approval sebagai inbox DM.')};
 @{h='Nilai koneksi dan audit platform';p=@('Instagram Professional, Facebook Page, TikTok, dan YouTube memiliki tipe akun, scope, dan review yang berbeda. Rubrik perlu mencatat status connected, missing scope, review pending, private-only, dan ready.','Uji reconnect setelah token expiry dan disconnect setelah kontrak berakhir. Pastikan alat tidak meminta password dan tidak menyembunyikan access token.','Video publishing harus dibuktikan dengan provider status, bukan request sukses. TikTok dan YouTube dapat membatasi unaudited atau unverified client ke private.')};
 @{h='Nilai analytics dan laporan';p=@('Tanyakan sumber metrics, periode, timezone, dan apa yang terjadi jika scope analytics tidak ada. Empty state yang jujur lebih baik daripada grafik nol yang mengesankan performa buruk.','Minta export mentah sebelum menyimpulkan angka. Jika laporan PDF memiliki logo, cek apakah data memiliki sumber, tanggal, dan checksum. Kelola Konten belum menjanjikan PDF branded sampai modul tersebut selesai.','Competitor analytics membutuhkan sumber data yang diizinkan dan tanggal pengambilan. Jangan memilih alat karena menampilkan skor kompetitor tanpa metodologi.')};
 @{h='Bangun scorecard dan keputusan';p=@('Buat scorecard dengan kolom workflow, evidence, limitation, owner, dan next test. Hindari angka bobot yang tidak memiliki alasan. Tulis inference sebagai inference.','Jalankan dua judge menggunakan tugas yang sama pada desktop dan 390 piksel. Catat waktu, error, dan screenshot. Demo dari vendor atau laporan builder bukan bukti independen.','Keputusan akhir menyebut alur yang lulus, gated, atau `segera`. Dengan format ini, agensi dapat mulai dari workflow yang tersedia sambil menyusun permintaan vendor.')}
);Faq=@(
 @{q='Apakah jumlah channel paling penting?';a='Tidak. Workflow, permission, approval, dan data ownership sering lebih menentukan. Channel harus diuji pada akun yang benar-benar dipakai.'};
 @{q='Bagaimana membandingkan harga?';a='Gunakan halaman harga resmi yang diambil pada tanggal tertentu. Run ini sengaja tidak mengisi harga karena belum diverifikasi dan belum disetujui owner.'};
 @{q='Apa tanda approval yang baik?';a='Komentar terikat pada draft, versi, status, timestamp, dan role. Perubahan besar mengembalikan status ke review.'};
 @{q='Mengapa competitor analytics perlu hati-hati?';a='Data harus berasal dari sumber yang diizinkan dan memiliki metodologi. Scraping atau skor tanpa sumber tidak layak dijadikan janji.'}
);Sources=@(@{n='Postiz README';u='https://github.com/gitroomhq/postiz-app/blob/main/README.md'},@{n='Postiz quickstart';u='https://github.com/gitroomhq/postiz-docs/blob/main/general/quickstart.mdx'},@{n='YouTube quota and audits';u='https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits'})}
