. 'D:\Projects\Kelola Konten\website\marketing\article-gen.ps1'
Write-Article @{Slug='inbox-komentar-media-sosial';Title='Inbox Komentar Media Sosial: Batas API dan Workflow yang Jujur';Primary='inbox komentar media sosial';Eyebrow='Panduan kolaborasi';Intro='Inbox komentar dan DM sering dijanjikan sebagai satu fitur, padahal setiap platform memiliki endpoint, scope, dan aturan sendiri. Artikel ini membedakan komentar internal, mentions, komentar eksternal, dan DM agar tim tidak membeli janji yang belum terbukti.';Sections=@(
 @{h='Bedakan empat jenis percakapan';p=@('Komentar internal adalah catatan anggota workspace pada draft atau post. Ia tidak terlihat di Instagram, Facebook, TikTok, atau YouTube. Postiz source memiliki kontrak komentar internal dan provider functions, sehingga fitur ini dapat diuji tanpa mengklaim inbox eksternal.','Komentar eksternal berasal dari post yang sudah terbit. DM adalah percakapan privat yang memerlukan endpoint dan permission berbeda. Mentions dapat memiliki alur lain. UI sebaiknya menampilkan source, post, thread, dan scope untuk setiap item.','Jika provider tidak mengembalikan data, tampilkan no data atau scope missing. Jangan menggabungkan semua tab menjadi satu daftar seolah setiap pesan dapat dibalas. Label `segera` memberi ekspektasi yang benar.')};
 @{h='Apa yang dibuktikan oleh Postiz';p=@('README Postiz menyebut kolaborasi, komentar, dan scheduling. Source provider memiliki method comment, mentions, analytics, dan function integration. Bukti ini cukup untuk merancang capability matrix, tetapi belum membuktikan unified DM inbox lintas platform.','Sebelum menjanjikan reply, uji provider satu per satu: baca komentar, kirim reply, tangani pagination, simpan external ID, dan cegah duplikasi. Simpan request/response redacted untuk audit.','Kelola Konten menempatkan internal comments sebagai beta. Unified external comments and DMs tetap `segera` hingga semua provider yang dijanjikan lolos test. Tombol segera dapat membuka waitlist atau roadmap, bukan composer palsu.')};
 @{h='Permission dan consent';p=@('Meta API untuk Instagram Professional memakai permission dan App Review sesuai jalur login. Page messaging dan Instagram messaging tidak otomatis aktif hanya karena publishing aktif. Scope yang tidak disetujui harus ditampilkan sebagai missing.','Jangan meminta password sosial. OAuth langsung dan disconnect menjaga kepatuhan. Simpan consent dan timestamp, lalu jelaskan data yang dibaca dan tindakan yang dikirim.','TikTok dan YouTube memiliki batas yang berbeda untuk komentar, sehingga jangan menyalin capability Instagram ke kanal lain tanpa bukti. Capability matrix mencatat supported, gated, dan unavailable.')};
 @{h='Desain inbox yang aman';p=@('Item inbox harus memiliki provider, account, external ID, timestamp, status, dan assignee. Balasan menyimpan idempotency key. Jika provider timeout, UI menunjukkan pending dan mencegah klik berulang.','Role menentukan siapa yang boleh reply atau assign. Audit menampilkan user dan waktu. Data privat tidak dikirim ke analytics. Retention dan delete policy harus ditulis sebelum fitur eksternal diluncurkan.','Search dan filter perlu membedakan komentar publik, DM privat, mention, dan internal note. Jika data tidak lengkap, lebih baik filter terbatas dengan label daripada hasil palsu.')};
 @{h='Handoff untuk tim saat ini';p=@('Sambil menunggu unified inbox, gunakan internal comments untuk review konten dan tautan platform native untuk membalas pelanggan. Kalender menyimpan pemilik tindakan dan status handoff.','Templated response tidak boleh otomatis dikirim tanpa consent dan permission. Reviewer membaca pesan di platform native lalu mencatat ringkasan non-sensitif di workspace.','Roadmap `segera` memiliki acceptance test yang eksplisit. Dengan begitu, tim dapat menilai kemajuan tanpa mengubah label setiap kali ada demo UI.')};
 @{h='Ukur nilai tanpa menyamarkan cakupan';p=@('Ukur waktu dari komentar diterima sampai pemilik mengakui handoff, bukan hanya jumlah item di inbox. Jika unified inbox belum ada, jangan sebut waktu respons aplikasi.','Analytics hanya digunakan ketika provider scope dan data tersedia. Sumber dan tanggal pengambilan ditampilkan. Metrik kosong bukan nol performa.','Setelah provider pertama lolos, jalankan dua judge pada desktop dan mobile. Perbaiki permission, pagination, dan retry sebelum menambah provider berikutnya.')}
);Faq=@(
 @{q='Apakah komentar internal adalah unified inbox?';a='Tidak. Komentar internal hanya ada di workspace. Unified inbox external memerlukan provider read/reply dan permission.'};
 @{q='Mengapa DM belum tersedia?';a='DM memiliki endpoint dan review berbeda per platform. Kelola Konten memberi label `segera` sampai kontrak provider dan test lulus.'};
 @{q='Bagaimana tim membalas sekarang?';a='Gunakan platform native melalui handoff yang dicatat pada kalender atau workspace. Jangan membuat composer yang tampak live tetapi tidak mengirim.'};
 @{q='Data apa yang perlu disimpan?';a='External ID, provider, thread, timestamp, status, assignee, dan audit. Token, password, dan isi privat tidak boleh masuk analytics.'}
);Sources=@(@{n='Postiz README';u='https://github.com/gitroomhq/postiz-app/blob/main/README.md'},@{n='Postiz social integration interface';u='https://github.com/gitroomhq/postiz-app/blob/main/libraries/nestjs-libraries/src/integrations/social/social.integrations.interface.ts'},@{n='Meta Instagram API collection';u='https://www.postman.com/meta/instagram/documentation/6yqw8pt/instagram-api'})}
