. 'D:\Projects\Kelola Konten\website\marketing\article-gen.ps1'
Write-Article @{Slug='upload-video-youtube-otomatis';Title='Upload Video YouTube Otomatis: OAuth, Processing, dan Batasan Project';Primary='upload video YouTube otomatis';Eyebrow='Panduan platform';Intro='Upload video YouTube dari aplikasi memerlukan OAuth, videos.insert, dan pemantauan processing. Project API yang belum diverifikasi dapat membatasi video menjadi private. Artikel ini menyusun workflow yang bisa diaudit untuk tim konten dan agensi.';Sections=@(
 @{h='Kenali resource dan scope';p=@('YouTube Data API menggunakan resource video dengan snippet, status, dan detail processing. Untuk upload, aplikasi memakai OAuth scope seperti youtube.upload. API key saja tidak cukup untuk menulis ke channel pengguna.','Kelola Konten menampilkan channel yang diotorisasi, expiry, scope, dan verification state. Pengguna dapat disconnect tanpa menempelkan credential manual. Token disimpan terenkripsi dan tidak pernah dimasukkan ke analytics event.','Buat project Google Cloud khusus aplikasi. Simpan client ID dan secret di environment operator. Redirect URI harus cocok persis dengan konfigurasi sehingga kegagalan OAuth dapat dibedakan dari penolakan permission.')};
 @{h='Buat video dengan metadata yang valid';p=@('Draft mencatat title, description, tags, category, privacyStatus, file, dan waktu publish. Field wajib divalidasi sebelum upload. Preview membantu menemukan judul kosong, karakter bermasalah, atau media yang terlalu besar.','Gunakan resumable upload agar koneksi yang terputus tidak mengulang seluruh file. Simpan upload session dan status chunk secara aman. Jika sesi kedaluwarsa, buat retry yang tidak membuat kartu kalender menjadi ganda.','Metadata harus berasal dari brief yang disetujui. Jangan menambahkan klaim atau link otomatis tanpa review. Simpan versi caption supaya perubahan setelah approved terlihat.')};
 @{h='Pahami private-until-audit';p=@('Referensi videos.insert menyatakan video dari unverified API project yang dibuat setelah 28 Juli 2020 dibatasi private sampai project diaudit. Copy produk harus menampilkan batasan ini sebagai status, bukan catatan tersembunyi.','Private upload tetap berguna untuk review internal, penjadwalan di YouTube Studio, atau pemeriksaan processing. Bedakan private, unlisted, dan public pada selector, lalu kunci pilihan yang tidak diizinkan provider.','Jangan menjadikan HTTP 200 sebagai bukti tayang. Simpan video ID, panggil videos.list dengan processingDetails, lalu baca status. URL publik hanya dapat disebut setelah visibility dan processing benar-benar terverifikasi.')};
 @{h='Pantau processing dan quota';p=@('Processing dapat berlangsung setelah videos.insert sukses. Queue menyimpan pending, succeeded, atau failed, dengan retry terbatas. Error detail ditampilkan kepada pemilik tanpa membocorkan token atau response mentah yang sensitif.','YouTube memakai quota. Dokumentasi menyebut default allocation dan bucket upload yang dapat berubah. Kelola Konten menampilkan quota error dan link sumber, tetapi tidak menjanjikan jumlah upload tetap di halaman pemasaran.','Buat health view untuk upload queue, waktu terakhir sukses, dan error terbaru. Operator dapat mengambil tindakan sebelum pengguna membuat banyak retry.')};
 @{h='Kolaborasi dan approval';p=@('Reviewer memeriksa title, thumbnail, description, privacy, dan link. Comment internal menempel pada draft. Jika file atau privacy berubah, status kembali review.','Agensi dapat menyimpan channel per workspace. Pengguna yang hanya reviewer tidak boleh mengganti OAuth atau menghapus video. Uji isolasi dua organisasi sebelum beta.','Laporan performa tidak boleh mengarang views saat data belum tersedia. Tampilkan processing atau no data dan timestamp pengambilan.')};
 @{h='Rencanakan peluncuran';p=@('Mulai dengan private test upload dan catat seluruh status. Ajukan audit jika use case dan compliance siap. Setelah audit, jalankan test publik dengan konten yang disetujui.','Artikel, status page, dan UI memakai bahasa yang sama: upload berhasil, processing berjalan, private-only, public verified, atau failed. Keseragaman istilah mengurangi permintaan dukungan.','Gunakan hasil test untuk memutuskan apakah video otomatis masuk beta. Jika audit belum selesai, tetap sediakan draft dan handoff, lalu labeli fase tersebut `bergantung persetujuan platform`.')}
);Faq=@(
 @{q='Mengapa video tetap private?';a='Project API yang belum diverifikasi dapat membatasi video ke private. Ikuti status audit dan dokumen YouTube sebelum menyebut video publik.'};
 @{q='Apakah API key dapat upload?';a='Upload memerlukan OAuth scope yang sesuai, seperti youtube.upload. API key saja tidak memberi otorisasi channel.'};
 @{q='Bagaimana memastikan upload selesai?';a='Simpan video ID, panggil videos.list untuk processingDetails, dan periksa status visibility setelah processing.'};
 @{q='Apakah quota selalu 10.000 unit?';a='Default quota dapat berubah dan upload memiliki aturan bucket. Link ke quota docs dan tampilkan error aktual.'}
);Sources=@(@{n='YouTube videos.insert';u='https://developers.google.com/youtube/v3/docs/videos/insert'},@{n='YouTube upload guide';u='https://developers.google.com/youtube/v3/guides/uploading_a_video'},@{n='YouTube quota and audits';u='https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits'})}
