. 'D:\Projects\Kelola Konten\website\marketing\article-gen.ps1'
Write-Article @{Slug='jadwal-posting-instagram-dari-laptop';Title='Jadwal Posting Instagram dari Laptop: Alur Aman untuk Tim Kecil';Primary='jadwal posting Instagram dari laptop';Eyebrow='Panduan platform';Intro='Menjadwalkan Instagram dari laptop membantu tim memeriksa naskah, aset, dan approval sebelum waktu tayang. Panduan ini membahas syarat akun profesional, koneksi, preview, status permission, serta cara menangani kegagalan tanpa mengklaim semua akun dapat dipublikasikan otomatis.';Sections=@(
 @{h='Siapkan akun dan akses yang benar';p=@('Instagram API ditujukan untuk akun profesional dengan jalur akses yang sesuai. Sebelum membuka composer, pastikan pemilik akun memberikan izin dan memahami aplikasi mana yang terhubung. Kelola Konten perlu menampilkan nama akun, tipe akun, waktu koneksi, dan scope yang diberikan agar reviewer tidak menebak.','Hubungkan Facebook Page jika jalur login yang dipilih membutuhkannya. Jangan menganggap akun personal dapat memakai semua endpoint. Jika Page atau akun profesional belum siap, berikan instruksi handoff dan simpan draft agar pekerjaan tidak hilang.','Simpan hanya token terenkripsi dan tampilkan tombol disconnect. Log operator harus menyamarkan token. Status connection, scope missing, atau review pending harus dapat dilihat pengguna tanpa membuka rahasia.')};
 @{h='Buat brief sebelum mengunggah';p=@('Tuliskan tujuan, audiens, hook, CTA, format, dan sumber aset di draft. Brief pendek membantu pemilik bisnis memberi feedback yang konkret. Jika caption memuat klaim produk, tautkan sumber atau pemilik fakta.','Unggah aset dari media library, lalu periksa rasio, ukuran, dan alt text. Preview di laptop bukan pengganti pemeriksaan pada aplikasi Instagram, tetapi membantu menemukan baris terpotong dan tautan yang salah.','Jika satu ide dipakai ulang, ubah konteks dan CTA dengan sengaja. Cross-posting tidak berarti caption dapat disalin mentah. Simpan versi per channel di bawah ID konten yang sama.')};
 @{h='Hubungkan dan periksa status OAuth';p=@('Mulai OAuth dari tombol Connect Instagram, bukan meminta pengguna menempelkan access token. Callback menyimpan provider, akun, scope, expiry, dan status review. Jika callback gagal, tampilkan penyebab aman dan tombol coba lagi.','Meta dapat membatasi permission sampai App Review. Akun test atau app-role dapat membantu pengembangan, tetapi status itu tidak sama dengan akses pelanggan produksi. Kelola Konten harus menampilkan badge test, review pending, atau ready sesuai data app.','Jalankan koneksi ulang ketika token kedaluwarsa. Jangan membuat akun baru otomatis. Audit trail mencatat siapa yang menghubungkan akun dan kapan, sehingga agensi bisa menjelaskan perubahan kepada klien.')};
 @{h='Jadwalkan dan validasi';p=@('Pilih waktu dengan zona WIB, lalu pilih target Instagram. Validation memeriksa teks, media, dan opsi yang provider dukung. Kartu jadwal harus menampilkan scheduled, published, failed, atau canceled.','Meta publishing memakai alur container lalu publish pada API. Jika provider mengembalikan error, simpan request ID dan ringkasan error, bukan token. Retry menggunakan idempotency agar satu jadwal tidak menjadi dua post.','Post now adalah jalur uji yang berbeda dari scheduled. Gunakan akun uji dan konten yang disetujui. Bukti sukses berupa URL provider atau status yang dapat diverifikasi, bukan hanya HTTP 200 dari backend.')};
 @{h='Review dan kolaborasi';p=@('Reviewer memeriksa fakta, visual, CTA, dan izin sebelum approve. Komentar internal ditempel pada draft. Jika edit besar dilakukan, status kembali ke review. Simpan user dan timestamp untuk audit.','Agensi dapat membuat workspace per klien sehingga kalender tidak tercampur. Role reviewer tidak boleh menghapus integrasi atau membaca workspace lain. Uji dua organisasi secara terpisah sebelum membuka beta.','Unified inbox komentar dan DM lintas platform tetap `segera` sampai provider read/reply benar-benar diuji. Komentar internal pada draft bukan bukti bahwa Kelola Konten sudah bisa membalas DM pelanggan.')};
 @{h='Baca hasil dan tangani batasan';p=@('Analytics hanya menampilkan data yang dikembalikan scope provider. Jika data kosong atau scope kurang, tampilkan penjelasan dan reconnect. Jangan mengisi 0 agar grafik tampak lengkap.','TikTok dan YouTube dapat memiliki pembatasan audit yang berbeda. Instagram juga bergantung pada permission dan tipe akun. Halaman status integrasi merangkum batasan dengan tautan dokumentasi resmi.','Setelah satu siklus, tinjau jadwal yang sukses, gagal, dan menunggu review. Pilih satu eksperimen caption atau waktu, lalu catat hipotesis. Jangan menyebut jam posting terbaik sebagai fakta universal.')}
);Faq=@(
 @{q='Apakah semua akun Instagram bisa dijadwalkan dari laptop?';a='Tidak. Dukungan mengikuti tipe akun, permission, dan status aplikasi. Tampilkan status koneksi sebelum menjanjikan publish.'};
 @{q='Mengapa post tertunda setelah HTTP 200?';a='API dapat menerima request lalu memproses container secara asinkron. Tunggu status provider dan simpan error jika finalisasi gagal.'};
 @{q='Apakah komentar internal sama dengan inbox DM?';a='Tidak. Komentar internal adalah kolaborasi workspace. Inbox DM memerlukan provider read/reply dan permission yang belum otomatis tersedia.'};
 @{q='Bagaimana jika App Review belum selesai?';a='Gunakan akun test atau simpan draft, lalu tampilkan review pending dan handoff. Jangan mengklaim akses produksi.'}
);Sources=@(@{n='Meta Instagram API collection';u='https://www.postman.com/meta/instagram/documentation/6yqw8pt/instagram-api'},@{n='Meta content publishing';u='https://developers.facebook.com/documentation/instagram-platform/content-publishing'},@{n='Postiz quickstart';u='https://github.com/gitroomhq/postiz-docs/blob/main/general/quickstart.mdx'})}
