. 'D:\Projects\Kelola Konten\website\marketing\article-gen.ps1'
Write-Article @{Slug='laporan-media-sosial-untuk-klien';Title='Laporan Media Sosial untuk Klien: Struktur yang Bisa Diaudit';Primary='laporan media sosial untuk klien';Eyebrow='Panduan laporan';Intro='Laporan klien harus menjelaskan apa yang diukur, dari mana datanya, dan tindakan apa yang dilakukan berikutnya. Artikel ini menyusun struktur laporan, batas data provider, approval angka, dan roadmap laporan PDF berlogo agensi di Kelola Konten yang masih berstatus `segera`.';Sections=@(
 @{h='Mulai dari tujuan dan periode';p=@('Tulis tujuan laporan sebelum memilih grafik. Tujuan dapat berupa evaluasi kampanye, review workflow, atau keputusan konten berikutnya. Periode, timezone, dan tanggal pengambilan harus terlihat pada halaman pertama.','Jangan campur post yang berbeda jendela waktu tanpa catatan. Jika data masih diproses, tulis processing. Jika scope hilang, tulis missing scope. Empty state tidak boleh berubah menjadi nol hanya supaya tabel terlihat penuh.','Setiap metric memiliki definisi. Reach, impressions, views, likes, comments, saves, shares, dan clicks bukan sinonim. Linkkan dokumentasi provider bila definisinya berubah.')};
 @{h='Sertakan sumber dan metodologi';p=@('Laporan menyimpan provider, account label, endpoint atau export, tanggal akses, dan metode agregasi. Untuk angka turunan seperti engagement rate, tampilkan rumus dan pembilang/penyebut.','Contoh angka di template harus diberi label hipotetis. Jangan memasukkan benchmark industri tanpa dataset dan sumber. Jika Anda membuat rekomendasi dari pola, tulis sebagai hipotesis dan rencana uji.','Kelola Konten menyimpan analytics snapshot dan status provider bila tersedia. Data yang gagal dibaca tetap tercatat sebagai error sehingga klien memahami kenapa ada kolom kosong.')};
 @{h='Tulis narasi yang dapat ditindaklanjuti';p=@('Mulai dengan tiga temuan singkat: apa yang terjadi, bukti, dan keputusan. Hindari narasi yang hanya menyebut grafik naik atau turun. Kaitkan temuan dengan post, pilar, dan workflow yang dapat diubah.','Setiap rekomendasi memiliki pemilik dan tanggal review. Misalnya, uji hook edukasi dengan variasi CTA pada siklus berikutnya. Jangan menulis “posting pada jam ini pasti terbaik” dari satu pengamatan.','Simpan komentar klien dan keputusan di workspace. Revisi laporan tidak menghapus versi lama. Audit ini berguna ketika angka berubah karena late data atau correction provider.')};
 @{h='Rancang branding tanpa menutupi sumber';p=@('Laporan berlogo agensi boleh memiliki warna dan identitas yang konsisten, tetapi sumber metric tetap terlihat. Logo tidak boleh mengesankan endorsement platform.','Header mencantumkan nama klien, periode, kanal, dan status data. Footer mencantumkan kode versi dan kontak yang telah disetujui. Jangan menambahkan harga atau jam dukungan yang belum dikonfirmasi.','PDF harus memiliki teks yang dapat diseleksi, tanggal, dan checksum file. Screenshot visual membantu QA, tetapi file dan data mentah menjadi bukti utama.')};
 @{h='Batas fitur Kelola Konten saat ini';p=@('Postiz source dan UI menunjukkan analytics dan collaboration, tetapi run ini belum membuktikan export PDF berlogo agensi. Karena itu halaman fitur memakai label `segera` dan tidak menyediakan tombol download palsu.','Roadmap report membutuhkan data contract, template, renderer, logo upload, source notes, dan judge data. Modul berpindah ke tersedia hanya setelah PDF dibuat dari data terverifikasi dan dibuka kembali untuk pemeriksaan.','Sambil menunggu, tim dapat export data atau membuat laporan manual melalui proses yang dicatat. Handoff manual lebih jujur daripada PDF kosong yang tampak selesai.')};
 @{h='Review bersama dua judge';p=@('Jalankan laporan pada desktop 1440 dan mobile 390 untuk memastikan tabel tidak terpotong. Dua judge independen memeriksa data dan tampilan tanpa memakai laporan builder sebagai bukti.','Judge data memeriksa sumber, rumus, periode, dan angka. Judge visual memeriksa hierarchy, logo, typography, dan readability. Temuan diperbaiki lalu diuji ulang oleh judge yang sama.','Setelah gate lulus, simpan URL atau file, checksum, screenshot, dan source list di recap. Jika belum lulus, tetap `segera` dan tulis gap.')}
);Faq=@(
 @{q='Apakah PDF branded sudah tersedia?';a='Belum menjadi fitur tersedia pada run ini. Kelola Konten menandainya `segera` sampai export dan verifikasi data selesai.'};
 @{q='Apa yang harus ada di laporan?';a='Tujuan, periode, sumber, definisi metric, angka, temuan, rekomendasi, pemilik tindakan, dan catatan keterbatasan.'};
 @{q='Mengapa angka kosong tidak boleh diisi nol?';a='Kosong dapat berarti scope hilang atau data belum tersedia. Nol berarti provider mengembalikan nol. Keduanya harus dibedakan.'};
 @{q='Apakah logo cukup sebagai bukti laporan?';a='Tidak. Sumber data, tanggal, rumus, dan file yang dapat diaudit tetap diperlukan.'}
);Sources=@(@{n='Postiz README';u='https://github.com/gitroomhq/postiz-app/blob/main/README.md'},@{n='Postiz social integration interface';u='https://github.com/gitroomhq/postiz-app/blob/main/libraries/nestjs-libraries/src/integrations/social/social.integrations.interface.ts'},@{n='Meta Instagram API collection';u='https://www.postman.com/meta/instagram/documentation/6yqw8pt/instagram-api'})}
