. 'D:\Projects\Kelola Konten\website\marketing\article-gen.ps1'
Write-Article @{Slug='jadwal-konten-tiktok-untuk-bisnis';Title='Jadwal Konten TikTok untuk Bisnis: Pahami Direct Post dan Status Audit';Primary='jadwal konten TikTok untuk bisnis';Eyebrow='Panduan platform';Intro='TikTok menyediakan Content Posting API, tetapi alur Direct Post memiliki syarat scope, persetujuan aplikasi, dan pembatasan untuk client yang belum diaudit. Panduan ini membantu bisnis menyusun workflow yang jujur dari koneksi sampai handoff, tanpa menyamakan upload dengan publikasi publik.';Sections=@(
 @{h='Bedakan upload, Direct Post, dan tayang publik';p=@('Content Posting API bukan satu tombol universal. Aplikasi meminta informasi creator, menginisialisasi post, lalu mengirim video ke server TikTok. Status akhir harus dibaca dari respons provider.','Client yang belum diaudit dapat dibatasi ke private viewing. TikTok juga menjelaskan pembatasan user dan viewership untuk client unaudited. Karena itu, copy Kelola Konten harus menyebut “Tayang otomatis setelah aplikasi lolos audit platform” ketika kondisi itu berlaku.','Upload-only atau handoff adalah alur berbeda. Jika creator perlu mengedit di aplikasi TikTok, simpan file dan instruksi dengan status menunggu tindakan manual. Jangan memberi label published sebelum URL publik terverifikasi.')};
 @{h='Siapkan video dan consent';p=@('Brief mencatat pemilik akun, caption, privacy, cover, dan apakah audio memiliki izin. Creator harus memberi consent untuk mengirim video dan metadata ke TikTok. Simpan bukti persetujuan di audit log tanpa menyimpan rahasia.','Periksa watermark dan materi promosi sesuai pedoman TikTok. Aplikasi tidak boleh menambahkan branding yang dilarang ke video yang dibagikan. Kelola Konten hanya memvalidasi aset yang dikirimnya, bukan menggantikan pemeriksaan creator.','Media library menyimpan versi asli dan versi yang dikirim. Hash file membantu membuktikan file yang dipakai. Bila video berubah, buat draft baru supaya riwayat tidak tertukar.')};
 @{h='Hubungkan scope dan status app';p=@('Aplikasi perlu terdaftar di TikTok for Developers, menambahkan Content Posting API, dan memperoleh persetujuan scope video.publish untuk Direct Post. UI menunjukkan scope granted, pending, atau missing.','Jangan meminta scope yang tidak digunakan. Review platform memeriksa use case dan perilaku aplikasi. Dokumentasikan redirect URI, app ID, dan waktu koneksi, lalu redaksikan token di semua log.','Jika scope belum disetujui, tombol Direct Post dapat dinonaktifkan dan diganti dengan Save draft atau Upload handoff. Pesan harus menyebut langkah berikutnya, bukan error generik.')};
 @{h='Susun kalender dengan private state';p=@('Kartu kalender menampilkan target TikTok, waktu, privacy, dan audit state. Untuk unaudited client, default private-only harus jelas sebelum pengguna menekan schedule. Pengguna dapat mengubah privacy setelah memenuhi syarat platform, bukan melalui janji dari aplikasi.','Simpan proses async dan polling. Jika upload berhasil tetapi publish belum selesai, status processing tidak boleh disebut failed. Jika provider menolak, tampilkan error yang aman dan link dokumentasi.','Pembatasan rate dan creator cap mengikuti aturan TikTok yang berlaku. Jangan menulis angka di halaman kecuali halaman resmi yang dipakai masih memuat angka itu dan tanggal akses dicatat.')};
 @{h='Handoff yang dapat dilacak';p=@('Handoff berisi file, caption, waktu target, dan pemilik tindakan. Setelah creator publish secara manual, pengguna memasukkan URL atau ID post untuk menutup tugas. Data ini membuat kalender tetap berguna tanpa berpura-pura API berhasil.','Agensi dapat menandai siapa yang bertanggung jawab atas upload. Reviewer memeriksa privacy dan caption sebelum file dikirim. Jika klien tidak memberikan URL, status tetap menunggu bukti, bukan published.','Handoff juga menjadi data untuk menilai hambatan. Hitung berapa post tertahan karena audit, bukan mengarang reach. Temuan ini dapat menjadi bahan keputusan apakah pengajuan audit layak.')};
 @{h='Evaluasi setelah audit';p=@('Setelah aplikasi diaudit, lakukan test publik dengan akun yang diizinkan dan simpan hasil. Uji tidak berarti semua format atau semua akun siap. Capability matrix perlu menyebut jenis media, scope, dan batas yang benar-benar diuji.','Analytics hanya dibaca jika scope dan endpoint tersedia. Private post tetap memiliki status platform sendiri. Pisahkan status publikasi dari performa agar laporan tidak menyalahartikan status private sebagai kegagalan konten.','Jadikan audit changelog terlihat pada halaman status. Tanggal perubahan, link sumber, dan akun uji membantu pengguna memahami kenapa perilaku berbeda dari bulan lalu.')}
);Faq=@(
 @{q='Apakah client unaudited bisa post publik?';a='Dokumentasi TikTok menyatakan konten client yang belum diaudit dibatasi private viewing. Tampilkan private-only dan siapkan handoff sampai audit selesai.'};
 @{q='Apa yang harus disetujui pengguna?';a='Pengguna menyetujui pengiriman video dan metadata, serta memilih privacy yang tersedia. Consent perlu dicatat tanpa menyimpan token di log.'};
 @{q='Bolehkah menambahkan watermark brand?';a='Pedoman TikTok melarang material promosi atau watermark tertentu pada konten yang dibagikan. Ikuti pedoman resmi dan jangan menambah branding otomatis.'};
 @{q='Apakah upload 200 berarti tayang?';a='Tidak. Upload, processing, dan public visibility adalah status berbeda. Tunggu status provider dan bukti URL.'}
);Sources=@(@{n='TikTok Direct Post reference';u='https://developers.tiktok.com/docs/en/content-posting-api-reference-direct-post'},@{n='TikTok Direct Post getting started';u='https://developers.tiktok.com/docs/en/content-posting-api-get-started'},@{n='TikTok content sharing guidelines';u='https://developers.tiktok.com/doc/content-sharing-guidelines'})}
