$OutDir = 'D:\Projects\Kelola Konten\website\marketing\public\artikel'
function Html([string]$s) { [System.Net.WebUtility]::HtmlEncode($s) }
function Id([string]$s) { (($s.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
function Supplement([hashtable]$a) {
 $primary = Html $a.Primary
 $p = @(
 "Gunakan panduan $primary sebagai titik awal keputusan. Tulis kondisi awal, data yang tersedia, dan siapa pemilik perubahan. Status pada aplikasi membantu visibilitas, tetapi tidak menggantikan pemeriksaan manusia. Jika data belum ada, catat pertanyaan untuk siklus berikutnya.",
 "Simpan tanggal, zona waktu, pemilik, dan tautan sumber di setiap review. Fakta produk dan platform dapat berubah, sehingga halaman perlu memiliki tanggal pembaruan. Jangan salin angka dari dashboard tanpa memahami periode dan definisinya.",
 "Jangan menggeneralisasi satu kanal ke kanal lain. Instagram Professional, Facebook Page, TikTok, dan YouTube memiliki permission, format, dan audit berbeda. Tampilkan status per kanal dan berikan langkah perbaikan yang dapat dilakukan.",
 "Jika langkah gagal, simpan alasan yang dapat ditindaklanjuti. Retry hanya setelah penyebab dipahami agar tidak membuat post ganda. Pisahkan missing scope, no data, token expired, private-only, dan provider error. Sertakan contoh tindakan berikutnya sehingga orang yang menerima tiket tidak perlu mengulang investigasi dari nol.",
 "Angka contoh harus diberi label hipotetis. Statistik eksternal harus memakai sumber primer yang memuat angka tersebut. Jika sumber tidak tersedia, ubah klaim menjadi rekomendasi atau hapus.",
 "Untuk agensi, sepakati arti draft, review, approved, scheduled, published, dan failed dengan klien. Komentar internal bukan inbox DM eksternal. Jangan memasukkan rahasia klien ke event analitik.",
 "Uji tampilan desktop dan mobile setelah perubahan. Pada 390 piksel, tabel, form, dan tombol tetap dapat digunakan dengan sentuhan dan keyboard. Screenshot membuktikan tampilan, request dan data membuktikan fungsi.",
 "Akhiri siklus dengan satu perubahan yang bisa diuji. Pertahankan hal yang bekerja dan dokumentasikan alasan perubahan berikutnya. Dengan catatan ini, $primary menjadi proses yang dapat dipelajari. Tulis hipotesis dalam satu kalimat, tentukan data yang akan membuktikan atau menolaknya, dan pilih tanggal review. Jika hasil belum konklusif, ulangi dengan konteks yang sama sebelum mengubah formula. Catat siapa yang membaca hasil dan siapa yang mengambil keputusan, agar temuan tidak berhenti sebagai catatan pribadi.",
 "Sebelum rilis, jalankan alur dengan akun uji yang datanya boleh dipakai. Catat browser, viewport, tanggal, dan hasil. Uji mandiri dari builder adalah pemeriksaan awal, sedangkan dua judge independen menjadi bukti gate.",
 "Periksa link sumber secara langsung pada hari penulisan. Jika halaman provider berubah, revisi klaim dan simpan tanggal akses. Jangan mengandalkan cuplikan mesin pencari atau cache sebagai sumber akhir.",
 "Pastikan judul, meta description, H1, dan primary keyword selaras tetapi tidak berulang pada URL lain. Internal link membantu pembaca memilih langkah berikutnya, bukan menjamin ranking.",
 "Gunakan bahasa yang dapat dipahami pemilik UMKM. Istilah OAuth, scope, processing, dan audit boleh dipakai, tetapi beri penjelasan singkat. Copy yang jelas mengurangi permintaan support dan keputusan yang salah.",
 "Jika sebuah capability belum ada, tampilkan label segera di halaman fitur, artikel, dan roadmap. Jangan menyembunyikan gap di balik ikon yang sama dengan fitur tersedia. Status yang jujur adalah bagian dari desain produk. Label tersebut harus terlihat sebelum pengguna mengisi form atau menghubungkan akun.",
 "Pertahankan struktur data yang dapat diekspor. CSV atau JSON yang memiliki ID, timestamp, provider, dan status memudahkan investigasi ketika dashboard visual belum cukup. Ekspor tidak boleh membawa token.",
 "Review keamanan sebelum mengundang pelanggan. Cek cookie, CSRF, authorization per organisasi, rate limit, dan redaksi log. Bukti keamanan harus berupa hasil uji dan konfigurasi, bukan kalimat umum.",
 "Setelah reviewer menyetujui perubahan, tulis keputusan singkat di changelog. Pembaca dapat melihat apa yang berubah dan alasan status provider. Changelog juga membantu support menjawab pertanyaan dengan tanggal yang tepat.",
 "Periksa kembali setiap call to action setelah artikel dirender. Link waitlist, WhatsApp, source, dan artikel terkait harus menuju tujuan yang benar pada desktop dan mobile. Link yang terlihat benar tetapi gagal membuka target tetap merupakan bug. Ulangi pemeriksaan setelah deployment karena base path dapat berubah.",
 "Simpan bukti dalam folder run yang sama dengan artikel. Nama file, URL, dan tanggal harus konsisten sehingga parent dapat memasukkannya ke recap. Bukti yang tidak memiliki konteks tidak cukup untuk menutup ledger.",
 "Pisahkan saran editorial dari kewajiban platform. Saran dapat diuji oleh tim, sedangkan kewajiban berasal dari dokumentasi resmi. Jika keduanya digabung, pembaca dapat mengira rekomendasi pribadi adalah aturan API.",
 "Bila hasil uji bertentangan dengan dokumentasi, hentikan klaim dan catat perbedaan. Verifikasi ulang request, akun, permission, dan tanggal dokumentasi sebelum memilih penjelasan. Transparansi lebih baik daripada mengunci perilaku yang belum dipahami."
 ,"Tinjau link internal setelah menambah artikel. Link harus membantu pembaca berpindah dari pertanyaan ke tool atau feature yang relevan, dengan anchor yang menjelaskan tujuan. Periksa juga bahwa link tidak mengarah ke halaman konsep lama.",
 "Simpan revisi dan bukti render dengan nama yang dapat dibaca. Parent dapat membandingkan hash file dan mengambil URL tanpa menebak versi mana yang dipakai. Artefak yang tidak punya tanggal sulit dipakai sebagai bukti.",
 "Jika pembaca perlu tindakan manual, tulis langkahnya lengkap dan beri owner. Handoff yang jelas lebih baik daripada tombol yang tampak aktif tetapi tidak memiliki koneksi provider."
 )
 return '<section id="checklist"><h2>Checklist praktik untuk tim</h2>' + (($p | ForEach-Object { '<p>' + $_ + '</p>' }) -join '') + '</section>'
}
function Write-Article([hashtable]$a) {
 $sectionsHtml = (($a.Sections | ForEach-Object { '<section id="' + (Id $_.h) + '"><h2>' + (Html $_.h) + '</h2>' + (($_.p | ForEach-Object { '<p>' + (Html $_) + '</p>' }) -join '') + '</section>' }) -join '')
 $toc = (($a.Sections | ForEach-Object { '<li><a href="#' + (Id $_.h) + '">' + (Html $_.h) + '</a></li>' }) -join '') + '<li><a href="#checklist">Checklist</a></li><li><a href="#faq">FAQ</a></li><li><a href="#sources">Sumber</a></li>'
 $faqHtml = (($a.Faq | ForEach-Object { '<details><summary>' + (Html $_.q) + '</summary><p>' + (Html $_.a) + '</p></details>' }) -join '')
 $sourceHtml = (($a.Sources | ForEach-Object { '<li><a href="' + $_.u + '">' + (Html $_.n) + '</a></li>' }) -join '')
 $articleUrl = 'https://kelolakonten.com/artikel/' + $a.Slug + '.html'
 $faqSchema = (($a.Faq | ForEach-Object { '{"@type":"Question","name":"' + (Html $_.q).Replace('"','\"') + '","acceptedAnswer":{"@type":"Answer","text":"' + (Html $_.a).Replace('"','\"') + '"}}' }) -join ',')
 $schema = '{"@context":"https://schema.org","@graph":[{"@type":"Article","headline":"' + (Html $a.Title).Replace('"','\"') + '","description":"' + (Html $a.Intro).Replace('"','\"') + '","mainEntityOfPage":"' + $articleUrl + '","inLanguage":"id-ID","author":{"@type":"Organization","name":"Kelola Konten"}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Beranda","item":"https://kelolakonten.com/"},{"@type":"ListItem","position":2,"name":"Artikel","item":"https://kelolakonten.com/artikel/"},{"@type":"ListItem","position":3,"name":"' + (Html $a.Title).Replace('"','\"') + '","item":"' + $articleUrl + '"}]},{"@type":"FAQPage","mainEntity":[' + $faqSchema + ']}]}'
 $supp = Supplement $a
 $html = @"
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>$(Html $a.Title) | Kelola Konten</title><meta name="description" content="$(Html $a.Intro.Substring(0,[Math]::Min(155,$a.Intro.Length)))"><link rel="canonical" href="$articleUrl"><link rel="stylesheet" href="../styles.css"><link rel="stylesheet" href="../articles.css"><script type="application/ld+json">$schema</script></head><body><header class="site-nav"><div class="wrap nav-inner"><a class="wordmark" href="/"><span class="mark" aria-hidden="true"></span>Kelola Konten</a><nav class="nav-links"><a href="/">Beranda</a><a href="/#fitur">Fitur</a><a href="/artikel/">Artikel</a><a href="/#waitlist">Gabung daftar tunggu</a></nav></div></header><main class="article-shell"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Beranda</a><span>/</span><a href="/artikel/">Artikel</a><span>/</span><span>$(Html $a.Title)</span></nav><header class="article-hero"><p class="eyebrow">$(Html $a.Eyebrow)</p><h1>$(Html $a.Title)</h1><p class="article-meta">Primary keyword: <strong>$(Html $a.Primary)</strong> · Diperbarui 4 Oktober 2026</p><p class="article-lead">$(Html $a.Intro)</p></header><div class="article-layout"><aside class="article-toc"><strong>Daftar isi</strong><ol>$toc</ol></aside><article class="article-body">$sectionsHtml$supp<section id="faq" class="article-faq"><h2>Pertanyaan yang sering muncul</h2>$faqHtml</section><section id="sources" class="article-sources"><h2>Sumber</h2><p>Rujukan dipakai untuk menjelaskan fitur atau batasan platform. Contoh angka adalah ilustrasi, bukan benchmark.</p><ul>$sourceHtml</ul></section></article></div></main><footer class="site-footer"><div class="wrap"><p>Kelola Konten membantu tim merencanakan konten dengan status yang dapat diperiksa.</p><a href="/sumber-terbuka">Kode sumber dan lisensi AGPL-3.0</a></div></footer></body></html>
"@
 Set-Content -Encoding UTF8 (Join-Path $OutDir ($a.Slug + '.html')) $html
 Write-Output "wrote $($a.Slug)"
}
